"""add Department

Revision ID: 44962b5807a3
Revises: 46a94e546432
Create Date: 2024-07-03 11:42:52.486805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44962b5807a3'
down_revision = '46a94e546432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
